src/Uoko.FireProj.WebSite/Controllers/OnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uoko.FireProj.Abstracts;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class OnlineController : BaseController
    {

        // GET: Online
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Detail(int taskId)
        {
            return View(taskId);
        }
        
    }
}

src/Uoko.FireProj.WebSite/Controllers/TaskController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using Mehdime.Entity;
using Newtonsoft.Json;
using Uoko.FireProj.DataAccess.Entity;
using Uoko.FireProj.DataAccess.Enum;
using Uoko.FireProj.Model;
using System.Security.Claims;
using Microsoft.AspNet.Identity.EntityFramework;
using Uoko.FireProj.Infrastructure.Data;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class TaskController : BaseController
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }

        public ActionResult Detail(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }
       
        public ActionResult Logs()
        {
            return View();
        }

        public ActionResult Seed()
        {
            throw new Exception("WTF");
            using (var dbScope = new DbContextScopeFactory().CreateReadOnly())
            {
                var db = dbScope.DbContexts.Get<FireProjDbContext>();
                db.SaveChanges();
            }

            return Json(null,JsonRequestBehavior.AllowGet);
        }
    }
}

src/Uoko.FireProj.WebSite/Views/Online/Detail.cshtml
@{
    ViewBag.Title = "上线任务详情";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Task")">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">上线详细</a>
        </li>
    </ul>
</div>

<div class="row" ng-controller="OnlineDetailController">
    <div class="col-md-12">

        <input id="onlineTaskId" name="onlineTaskId" value="@Model" type="hidden">

        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-fire"></i>上线详情
                </div>
            </div>

            <div class="portlet-body">

                <div>
                    <div class="row static-info">

                        <div class="col-md-2 name">
                            项目名称:
                        </div>
                        <div class="col-md-2 value">
                            <span ng-bind="onlineDetails.OnlineTask.ProjectName"></span>
                        </div>
                        <div class="col-md-2 name">
                            部署域名:
                        </div>
                        <div class="col-md-2 value">
                            <a ng-href="{{onlineDetails.OnlineTask.Domain}}" ng-bind="onlineDetails.OnlineTask.Domain" target="_blank"></a>
                        </div>
                        <div class="col-md-2 name">
                            上线版本:
                        </div>
                        <div class="col-md-2 value">
                            <span ng-bind="onlineDetails.OnlineTask.OnlineVersion"></span>
                        </div>
                    </div>
                    <div class="row static-info">
                        <div class="col-md-2 name">
                            部署服务器:
                        </div>
                        <div class="col-md-2 value">
                            <span ng-bind="onlineDetails.OnlineTask.DeployServerName"></span>
                        </div>
                        <div class="col-md-2 name">
                            服务器 IP:
                        </div>
                        <div class="col-md-2 value">
                            <span ng-bind="onlineDetails.OnlineTask.DeployServerIP"></span>
                        </div>
                        <div class="col-md-2 name">
                            部署状态:
                        </div>
                        <div class="col-md-2 value" title="{{(onlineDetails.OnlineTask.DeployStatus | DeployStatusFilter).Title}}">
                            <span ng-class="(onlineDetails.OnlineTask.DeployStatus | DeployStatusFilter).IconClass" ng-if="onlineDetails.OnlineTask"></span>
                            <a ng-href="{{buildInfoLink}}" target="_blank" ng-if="onlineDetails.OnlineTask.DeployStatus != 0">查看</a>
                            <a href="javascript:;" ng-click="retryDeploy()" ng-if="onlineDetails.OnlineTask.DeployStatus == 1" >重试</a>
                        </div>
                    </div>
                    <div class="row static-info">
                        <div class="col-md-2 name">
                            创建信息:
                        </div>
                        <div class="col-md-4 value">
                            <span ng-bind="onlineDetails.OnlineTask.CreatorName"></span> -
                            <span ng-bind="onlineDetails.OnlineTask.CreateDate | date:'yyyy-MM-dd HH:mm:ss'"></span>
                        </div>
                        <div class="col-md-2 name">
                            修改信息:
                        </div>
                        <div class="col-md-4 value">
                               <span ng-bind="onlineDetails.OnlineTask.ModifierName"></span> -
                            <span ng-bind="onlineDetails.OnlineTask.ModifyDate | date:'yyyy-MM-dd HH:mm:ss'"></span>
                        </div>
                    </div>
                </div>
              


                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-condensed">
                        <thead>
                        <tr>
                            <th rowspan="2">任务名称</th>
                            <th rowspan="2">分支</th>
                            <th colspan="2">TEST</th>
                            <th colspan="2">Pre</th>
                            <th colspan="2">Online</th>
                            <th rowspan="2">发起人</th>
                            <th rowspan="2">最后操作人</th>
                        </tr>
                        <tr>
                            <th>部署</th>
                            <th>测试</th>
                            <th>部署</th>
                            <th>测试</th>
                            <th>部署</th>
                            <th>测试</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="task in onlineDetails.TaskBelongOnline">
                            <td><a class="text-primary" href="/Task/Detail?taskId={{task.TaskInfo.Id}}">{{task.TaskInfo.TaskName}}</a> </td>
                            <td>{{task.TaskInfo.Branch}}</td>
                            <td title="{{(task.DeployInfoIoc.DeployStatus | DeployStatusFilter).Title}}">
                                <div ng-if="task.DeployInfoIoc">
                                    <span ng-class="(task.DeployInfoIoc.DeployStatus | DeployStatusFilter).IconClass"></span>
                                </div>
                            </td>
                            <td title="{{task.IocTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.IocTestAllPassed"></span>
                            </td>
                            <td title="{{(task.DeployInfoPre.DeployStatus | DeployStatusFilter).Title}}">
                                <span ng-class="(task.DeployInfoPre.DeployStatus | DeployStatusFilter).IconClass" ng-if="task.DeployInfoPre"></span>
                            </td>
                            <td title="{{task.PreTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.PreTestAllPassed"></span>
                            </td>
                            <td title="{{(task.OnlineTaskInfo.DeployStatus | DeployStatusFilter).Title}}">
                                <span ng-class="(task.OnlineTaskInfo.DeployStatus | DeployStatusFilter).IconClass" ng-if="task.OnlineTaskInfo"></span>
                            </td>
                            <td title="{{task.OnlineTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.OnlineTestAllPassed"></span>
                            </td>
                            <td title="{{task.TaskInfo.CreateDate | date:'yyyy-MM-dd HH:mm:ss'}}">{{task.TaskInfo.CreatorName}}</td>
                            <td title="{{task.TaskInfo.ModifyDate | date:'yyyy-MM-dd HH:mm:ss'}}">{{task.TaskInfo.ModifierName}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->

    </div>
</div>

@section Scripts {
        <script src="~/app/services/ProjectService.js"></script>
    <script src="~/app/services/TaskService.js"></script>
    <script src="~/app/filters/CommonFilter.js"></script>
    <script src="~/app/controllers/OnlineDetail.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Online/Index.cshtml
@{
    ViewBag.Title = "上线列表";
}
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Task")">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Index", "Online")">上线列表</a>
        </li>
    </ul>
</div>

<div class="row" ng-controller="OnlineListController">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-bullhorn"></i>上线列表
                </div>
            </div>
            <div class="portlet-body">
                <form role="form" class="form form-horizontal" name="form" ng-submit="Fire(form.$valid)">
                    <div class="form-body">
                        <div class="form-group form-md-line-input">
                            <label class="col-md-2 control-label">项目</label>
                            <div class="col-md-10">
                                <select class="form-control" name="project" ng-model="projectSelected" ng-change="Query()" ng-options="project.ProjectName for project in projects track by project.Id" required></select>
                                <div ng-if="form.$submitted || form.project.$touched">
                                    <span class="error-msg" ng-if="form.project.$error.required">请选择项目</span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group form-md-line-input">
                            <label class="col-md-2 control-label">部署服务器</label>
                            <div class="col-md-10">
                                <select name="server" class="form-control" ng-model="serverSelected" ng-options="server.Name for server in servers track by server.Id" required></select>
                                <div class="" ng-if="form.$submitted || form.server.$touched">
                                    <span class="error-msg" ng-if="form.server.$error.required">请选择服务器</span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group form-md-line-input">
                            <label class="col-md-2 control-label">域名</label>
                            <div class="col-md-10">
                                <select name="domain" class="form-control" ng-model="domainSelected" ng-options="domain.Name for domain in domains track by domain.Name" required></select>
                                <div ng-if="form.$submitted || form.domain.$touched">
                                    <span class="error-msg" ng-if="form.domain.$error.required">域名必选.</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input" ng-show="projectSelected.OnlineVersion">
                            <label class="col-md-2 control-label">
                                当前版本
                            </label>
                            <div class="col-md-10 value">
                                <span ng-bind="projectSelected.OnlineVersion"></span>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input">
                            <label class="col-md-2 control-label">
                                <a target="_blank" href="http://semver.org/lang/zh-CN/">上线版本</a>
                            </label>
                            <div class="col-md-10">
                                <input name="onlineVersion" ng-model="onlineVersion" class="form-control ng-pristine ng-invalid ng-invalid-required ng-touched" placeholder="主版本.次版本.修订版本" required="" type="text">
                            </div>
                        </div>

                    </div>
                    <div class="form-actions right">
                        <button ng-if="showFire==false" disabled  class="btn blue" ng-click=""><i class="fa fa-fire"></i>Fire </button>
                        <button ng-if="showFire==true" type="submit" class="btn blue" ng-click=""><i class="fa fa-fire"></i>Fire </button>
                    </div>

                </form>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-condensed">
                        <thead>
                        <tr>
                            <th rowspan="2">任务名称</th>
                            <th rowspan="2">分支</th>
                            <th colspan="2">Test</th>
                            <th colspan="2">Pre</th>
                            <th colspan="2">Online</th>
                            <th rowspan="2">发起人</th>
                            <th rowspan="2">最后操作人</th>
                        </tr>
                        <tr>
                            <th>部署</th>
                            <th>测试</th>
                            <th>部署</th>
                            <th>测试</th>
                            <th>部署</th>
                            <th>测试</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="task in taskInfos">
                            <td><a class="text-primary" href="/Task/Detail?taskId={{task.TaskInfo.Id}}">{{task.TaskInfo.TaskName}}</a> </td>
                            <td>{{task.TaskInfo.Branch}}</td>
                            <td title="{{(task.DeployInfoIoc.DeployStatus | DeployStatusFilter).Title}}">
                                <div ng-if="task.DeployInfoIoc">
                                    <span ng-class="(task.DeployInfoIoc.DeployStatus | DeployStatusFilter).IconClass" ></span>
                                </div>
                            </td>
                            <td title="{{task.IocTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.IocTestAllPassed"></span>
                            </td>
                            <td title="{{(task.DeployInfoPre.DeployStatus | DeployStatusFilter).Title}}">
                                <span ng-class="(task.DeployInfoPre.DeployStatus | DeployStatusFilter).IconClass" ng-if="task.DeployInfoPre" ></span>
                            </td>
                            <td title="{{task.PreTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.PreTestAllPassed"></span>
                            </td>
                            <td title="{{(task.OnlineTaskInfo.DeployStatus | DeployStatusFilter).Title}}">
                                <span ng-class="(task.OnlineTaskInfo.DeployStatus | DeployStatusFilter).IconClass" ng-if="task.OnlineTaskInfo"></span>
                            </td>
                            <td title="{{task.OnlineTestAllPassed ? '测试全部通过' : ''}}">
                                <span class="glyphicon glyphicon-ok" ng-if="task.OnlineTestAllPassed"></span>
                            </td>
                            <td title="{{task.TaskInfo.CreateDate | date:'yyyy-MM-dd HH:mm:ss'}}">{{task.TaskInfo.CreatorName}}</td>
                            <td title="{{task.TaskInfo.ModifyDate | date:'yyyy-MM-dd HH:mm:ss'}}">{{task.TaskInfo.ModifierName}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->

    </div>
</div>

@section Scripts {
    <script src="~/app/services/ProjectService.js"></script>
    <script src="~/app/services/TaskService.js"></script>
    <script src="~/app/filters/CommonFilter.js"></script>
    <script src="~/app/controllers/OnlineList.js"></script>
}