src/Uoko.FireProj.WebSite/Controllers/SystemSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class SystemSetController : BaseController
    {
        // GET: SystemSet
        #region 数据字典
        public ActionResult DictionaryMgmt()
        {
            return View("~/Views/Dictionary/Index.cshtml");
        }

        public ActionResult DictionaryForm()
        {
            return View("~/Views/Dictionary/Form.cshtml");
        }
        #endregion

        #region 域名资源
        public ActionResult DomainResourceMgmt()
        {
            return View("~/Views/DomainResource/Index.cshtml");
        }
    
        #endregion

        #region 服务器管理
        public ActionResult ServerMgmt()
        {
            return View("~/Views/Server/Index.cshtml");
        }

        public ActionResult Creat()
        {
            return View("~/Views/Server/Creat.cshtml");
        }
        public ActionResult Edit()
        {
            return View("~/Views/Server/Edit.cshtml");
        }

        public ActionResult Detail()
        {
            return View("~/Views/Server/Detail.cshtml");
        }
        #endregion

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
        }
    }
}

src/Uoko.FireProj.WebSite/Controllers/TaskController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using Mehdime.Entity;
using Newtonsoft.Json;
using Uoko.FireProj.DataAccess.Entity;
using Uoko.FireProj.DataAccess.Enum;
using Uoko.FireProj.Model;
using System.Security.Claims;
using Microsoft.AspNet.Identity.EntityFramework;
using Uoko.FireProj.Infrastructure.Data;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class TaskController : BaseController
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }

        public ActionResult Detail(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }
       
        public ActionResult Logs()
        {
            return View();
        }

        public ActionResult Seed()
        {
            throw new Exception("WTF");
            using (var dbScope = new DbContextScopeFactory().CreateReadOnly())
            {
                var db = dbScope.DbContexts.Get<FireProjDbContext>();
                db.SaveChanges();
            }

            return Json(null,JsonRequestBehavior.AllowGet);
        }
    }
}

src/Uoko.FireProj.WebSite/Views/Server/Creat.cshtml
@{
    ViewBag.Title = "服务器新增";
}
@section Css {
<link href="~/Metronic/assets/global/plugins/easyUI/easyui.css" rel="stylesheet" />
<link href="~/Metronic/assets/global/plugins/easyUI/icon.css" rel="stylesheet" />
}
<div class="col-md-12">
    <div ng-controller="ServerController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("ServerMgmt","SystemSet")">服务器管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">服务器新增</a>

                </li>
            </ul>

        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i>服务器新增
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                    <div class="portlet-body form">
                        <div id="bootstrap_alerts_demo"></div>
                        <form role="form" class="form-horizontal" name="serverForm" novalidate>
                            <div class="form-body">
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器名称</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.Name" placeholder="请输入服务器名称" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器名称是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器IP</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.IP" placeholder="请输入服务器IP" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器IP是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">环境</label>
                                    <div class="col-md-10">
                                        <select name="deployenvironment" class="form-control" ng-model="model.StageType" required>
                                            <option ng-repeat="environment in environmentList" value="{{environment.Id}}" >{{environment.Name}}</option>
                                        </select>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">环境必选</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">储路路径</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.PackageDir" placeholder="请输入储路路径" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">储路路径是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">描述</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" rows="3" ng-model="model.ServerDesc"></textarea>
                                        <div class="form-control-focus">
                                        </div>
                                    </div>

                                </div>

                                <div class="portlet box blue">
                                    <div class="portlet-title">
                                        <div class="caption">
                                            <i class="fa fa-cog"></i>IIS配置
                                        </div>
                                        <div class="actions">
                                            <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="append()"><i class="fa fa-plus"></i> 新 增</a>
                                            <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="removeit()"><i class="fa fa-minus"></i> 删 除</a>
                                            <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="accept()"><i class="fa fa-check-circle"></i> 保 存</a>
                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <table id="dg"></table> 
                                    </div>
                                        

                                </div>
                          
                                
                            </div>
                            
                            <div class="form-actions right">
                                <a class="btn default" href="@Url.Action("ServerMgmt","SystemSet")">取消</a>
                                <a class="btn blue" ng-disabled="serverForm.$invalid" ng-click="SubmitFrom(model)"><i class="fa fa-check"></i> 保存</a>
                            </div>
                        </form>
			        </div>
                </div>
            </div>
        </div>
        <!--END Form -->
    </div>
</div>

@section Scripts {
<script src="~/app/controllers/ServerCreate.js"></script>
<script src="~/app/services/ServerServer.js"></script>
<script src="~/app/services/TaskService.js"></script>
<script src="~/app/services/ProjectService.js"></script>
<script src="~/Metronic/assets/global/plugins/easyUI/jquery.easyui.min.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Server/Detail.cshtml
@{
    ViewBag.Title = "服务器查看";
}
@section Css {
<link href="~/Content/app.css" rel="stylesheet" />
<link href="~/Content/angular-ui-tree.min.css" rel="stylesheet" />
}
<div class="col-md-12">
    <div ng-controller="ServerController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("ServerMgmt","SystemSet")">服务器管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">服务器查看</a>

                </li>
            </ul>

        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-file-text-o"></i>服务器详情
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                    <div class="portlet-body form">
                        <div id="bootstrap_alerts_demo"></div>
                        <form role="form" class="form form-horizontal" name="serverForm" novalidate>
                            <div class="form-body">
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器名称</label>
                                    <div class="col-md-10">
                                        <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.Name" placeholder="请输入服务器名称" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器名称是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器IP</label>
                                    <div class="col-md-10">
                                        <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.IP" placeholder="请输入服务器IP" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器IP是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">环境</label>
                                    <div class="col-md-10">
                                        <select disabled name="deployenvironment" class="form-control" ng-model="model.StageType" required>
                                            <option ng-repeat="environment in environmentList" value="{{environment.Id}}" ng-selected="environment.Id==model.StageType">{{environment.Name}}</option>
                                        </select>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">环境必选</span>
                                    </div>

                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">储路路径</label>
                                    <div class="col-md-10">
                                        <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.PackageDir" placeholder="请输入储路路径" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">储路路径是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">描述</label>
                                    <div class="col-md-10">
                                        <textarea disabled class="form-control" rows="3" ng-model="model.ServerDesc"></textarea>
                                        <div class="form-control-focus">
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="form-actions right">
                                <a class="btn default" href="@Url.Action("ServerMgmt","SystemSet")">返回列表</a>
                            </div>

                        </form>
                       
			        </div>
                </div>
            </div>
        </div>
        <!--END Form -->
    <input type="hidden" id="id" value="@Html.ViewContext.RouteData.Values["id"]" />
    </div>
</div>
@section Scripts {
<script src="~/app/controllers/ServerDetail.js"></script>
<script src="~/app/services/ServerServer.js"></script>
<script src="~/app/services/TaskService.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Server/Edit.cshtml
@{
    ViewBag.Title = "服务器编辑";
}
@section Css {
<link href="~/Metronic/assets/global/plugins/easyUI/easyui.css" rel="stylesheet" />
<link href="~/Metronic/assets/global/plugins/easyUI/icon.css" rel="stylesheet" />
}
<div class="col-md-12">
    <div ng-controller="ServerController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("ServerMgmt","SystemSet")">服务器管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">服务器编辑</a>

                </li>
            </ul>

        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i>服务器编辑
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                    <div class="portlet-body form">
                        <div id="bootstrap_alerts_demo"></div>
                        <form role="form" class="form-horizontal" name="serverForm" novalidate>
                            <div class="form-body">
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器名称</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.Name" placeholder="请输入服务器名称" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器名称是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">服务器IP</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.IP" placeholder="请输入服务器IP" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">服务器IP是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">环境</label>
                                    <div class="col-md-10">
                                        <select name="deployenvironment" class="form-control" ng-model="model.StageType" required>
                                            <option ng-repeat="environment in environmentList" value="{{environment.Id}}" ng-selected="environment.Id==model.StageType">{{environment.Name}}</option>
                                        </select>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">环境必选</span>
                                    </div>

                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">储路路径</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.PackageDir" placeholder="请输入储路路径" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">储路路径是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">描述</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" rows="3" ng-model="model.ServerDesc"></textarea>
                                        <div class="form-control-focus">
                                        </div>
                                    </div>

                                </div>
                            
                            </div>
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cog"></i>IIS配置
                                    </div>
                                    <div class="actions">
                                        <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="append()"><i class="fa fa-plus"></i> 新 增</a>
                                        <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="removeit()"><i class="fa fa-minus"></i> 删 除</a>
                                        <a href="javascript:void(0)" class="btn btn-default btn-sm" onclick="accept()"><i class="fa fa-check-circle"></i> 保 存</a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <table id="dg"></table>
                                </div>
                            </div>
                           
                            <div class="form-actions right">
                                <a class="btn default" href="@Url.Action("ServerMgmt","SystemSet")">取消</a>
                                <a class="btn blue" ng-disabled="serverForm.$invalid" ng-click="SubmitFrom(model)"><i class="fa fa-check"></i> 保存</a>
                            </div>

                        </form>
                       
			        </div>
                </div>
            </div>
        </div>
        <!--END Form -->
    <input type="hidden" id="id" value="@Html.ViewContext.RouteData.Values["id"]" />
    </div>
</div>
@section Scripts {
<script src="~/app/controllers/ServerEdit.js"></script>
<script src="~/app/services/ServerServer.js"></script>
<script src="~/app/services/TaskService.js"></script>
<script src="~/Metronic/assets/global/plugins/easyUI/jquery.easyui.min.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Server/Index.cshtml
@{
    ViewBag.Title = "服务器管理";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Task")">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("ServerMgmt", "SystemSet")">服务器</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">服务器列表</a>
        </li>
    </ul>
</div>
<div ng-controller="ServerController">
    <!-- Grid -->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cog"></i>服务器列表
            </div>
            <div class="tools">
                <a href="javascript:;" class="reload" data-original-title="" title="刷新" ng-click="Query()"></a>
            </div>
            <div class="actions">
                <a id="sample_editable_1_new" class="btn btn-default btn-sm" href="@Url.Action("Creat","SystemSet")">
                    <i class="fa fa-plus"></i> 新 增 
                </a>
            </div>
        </div>
        <div class="portlet-body">

            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>服务器名称</th>
                            <th>服务器IP</th>
                            <th>环境</th>
                            <th>存储路径</th>
                            <th>描述</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="item in items">
                            <td>{{item.Name}}</td>
                            <td>{{item.IP}}</td>
                            <td>{{item.StageType|StageTypeFilter}}</td>
                            <td>{{item.PackageDir}}</td>
                            <td>{{item.ServerDesc}}</td>
                            <td >
                                <div >
                                    <a class="btn btn-success btn-xs" href="/SystemSet/Edit/{{item.Id}}">编辑</a>
                                    @*<a class="btn btn-success btn-xs" ng-click="delete(item)">删除</a>*@
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pull-right">
                        <uib-pagination total-items="totalItems" ng-model="currentPage" ng-change="Query()" first-text="首页" last-text="末页"
                                        previous-text="上一页" next-text="下一页" items-per-page="pageSize" max-size="5" boundary-links="true" boundary-link-numbers="true" rotate="false"></uib-pagination>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Grid -->
</div>


@section Scripts {
<script src="~/app/controllers/ServerList.js"></script>
<script src="~/app/services/ServerServer.js"></script>
<script src="~/app/filters/CommonFilter.js"></script>

}