src/Uoko.FireProj.WebSite/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class ProjectController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Creat()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }
    }
}

src/Uoko.FireProj.WebSite/Controllers/TaskController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using Mehdime.Entity;
using Newtonsoft.Json;
using Uoko.FireProj.DataAccess.Entity;
using Uoko.FireProj.DataAccess.Enum;
using Uoko.FireProj.Model;
using System.Security.Claims;
using Microsoft.AspNet.Identity.EntityFramework;
using Uoko.FireProj.Infrastructure.Data;

namespace Uoko.FireProj.WebSite.Controllers
{
    public class TaskController : BaseController
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }

        public ActionResult Detail(int taskId)
        {
            ViewBag.TaskId = taskId;
            return View();
        }
       
        public ActionResult Logs()
        {
            return View();
        }

        public ActionResult Seed()
        {
            throw new Exception("WTF");
            using (var dbScope = new DbContextScopeFactory().CreateReadOnly())
            {
                var db = dbScope.DbContexts.Get<FireProjDbContext>();
                db.SaveChanges();
            }

            return Json(null,JsonRequestBehavior.AllowGet);
        }
    }
}

src/Uoko.FireProj.WebSite/Views/Project/Creat.cshtml
@{
    ViewBag.Title = "项目新增";
}
@section Css {

<link href="~/Metronic/assets/global/plugins/zTree/css/zTreeStyle/zTreeStyle.css" rel="stylesheet"/>
}

<div class="col-md-12">
    <div ng-controller="ProjectController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Project")">项目管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">项目新增</a>

                </li>
            </ul>

        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i>项目新增
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                    <div class="portlet-body form">
                        <div id="bootstrap_alerts_demo"></div>
                        <form role="form" class="form form-horizontal" name="serverForm" novalidate>
                            <div class="form-body">
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">项目名称</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="form_control_1" ng-model="model.ProjectName" placeholder="请输入项目名称" required>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">项目名称是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">GitLab地址</label>
                                    <div class="col-md-10">

                                        <ui-select ng-model="model.Project" ng-change="GetProjectInfo(model.Project)" required>
                                            <ui-select-match>
                                                <span ng-bind="$select.selected.name"></span>
                                            </ui-select-match>
                                            <ui-select-choices repeat="item in (ProjectList | filter: $select.search) track by item.id">
                                                <span ng-bind="item.name"></span>
                                            </ui-select-choices>
                                        </ui-select>

                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">项目地址是必填</span>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">Sln名称</label>
                                    <div class="col-md-10">
                                        <input disabled type="text" class="form-control" id="ProjectSlnName" ng-model="model.ProjectSlnName" placeholder="请点击选择">
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn default btn-sm green"    ng-click="showMenu('sln')" ng-disabled="!showSln">
                                            选择
                                        </button>
                                         <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">项目文件是必填</span>
                                    </div>

                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">Csproj名称</label>
                                    <div class="col-md-10">
                                        <input disabled type="text" class="form-control" id="ProjectCsprojName" ng-model="model.ProjectCsprojName" placeholder="请点击选择">
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn default btn-sm green"  ng-click="showMenu('csproj')"  ng-disabled="!showSln">
                                            选择
                                        </button>
                                        <div class="form-control-focus">
                                        </div>
                                        <span class="help-block">Csproj是必选</span>
                                    </div>

                                </div>
                                <div class="form-group form-md-line-input">
                                    <label class="col-md-2 control-label" for="form_control_1">项目描述</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" rows="3" ng-model="model.ProjectDesc"></textarea>
                                        <div class="form-control-focus">
                                        </div>

                                    </div>
                                </div>

                            </div>
                            <div class="form-actions right">
                                <a  class="btn default" href="@Url.Action("Index","Project")">取消</a>
                                <a  class="btn blue" ng-disabled="serverForm.$invalid" ng-click="SubmitFrom(model)"><i class="fa fa-check"></i> 保存</a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" >
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">请选择</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div id="menuContent" style="border:1px solid #808080;">
                                                <ul id="treeDemo" class="ztree" style="width: 100%;"></ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
			        </div>
                </div>
           
            </div>
       
        </div>
        <!--END Form -->
   
    </div>

@section Scripts {
<script src="~/app/controllers/ProjectCreat.js"></script>
<script src="~/app/services/ProjectService.js"></script>
<script src="~/Metronic/assets/global/plugins/zTree/js/jquery.ztree.core-3.5.min.js"></script>


}

src/Uoko.FireProj.WebSite/Views/Project/Detail.cshtml
@{
    ViewBag.Title = "项目查看";
}
<div class="col-md-12">
    <div ng-controller="ProjectController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Project")">项目管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">项目查看</a>

                </li>
            </ul>

        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-book"></i>项目详细
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                <div class="portlet-body form">
                    <div id="bootstrap_alerts_demo"></div>
                    <form role="form" class="form-horizontal" name="serverForm" novalidate>
                        <div class="form-body">
                            <div class="form-group form-md-line-input">
                                <label  class="col-md-2 control-label" for="form_control_1">项目名称</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.ProjectName" placeholder="请输入项目名称" required>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目名称是必填</span>
                                </div>
                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">GitLab地址</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.ProjectRepo"  required>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目地址是必填</span>
                                </div>
                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">Sln名称</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.ProjectSlnName" placeholder="选择项目自动带出" required>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目文件是必填</span>
                                </div>

                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">Csproj名称</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="ProjectCsprojName" ng-model="model.ProjectCsprojName" placeholder="请点击选择">
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">Csproj是必选</span>

                                </div>

                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">项目描述</label>
                                <div class="col-md-10">
                                    <textarea disabled class="form-control" rows="3" ng-model="model.ProjectDesc"></textarea>
                                    <div class="form-control-focus">
                                    </div>

                                </div>
                            </div>

                        </div>
                        <div class="form-actions right">
                             <a type="button" class="btn default " href="@Url.Action("Index","Project")">返回列表</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <!--END Form -->
        <input type="hidden" id="id" value="@Html.ViewContext.RouteData.Values["id"]" />
    </div>
</div>
@section Scripts {
<script src="~/app/controllers/ProjectDetail.js"></script>
<script src="~/app/services/ProjectService.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Project/Edit.cshtml
@{
    ViewBag.Title = "项目编辑";
}
<div class="col-md-12">
    <div ng-controller="ProjectController">
        <!-- BEGIN  HEADER-->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">主页</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Project")">项目管理</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">项目编辑</a>
                </li>
            </ul>
        </div>
        <!-- END  HEADER-->
        <!--BEGIN Form -->
        <div>
            <div class="portlet  box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plus"></i>项目编辑
                    </div>
                    <div class="actions">
                       
                    </div>
                </div>
                <div class="portlet-body form">
                    <div id="bootstrap_alerts_demo"></div>
                    <form role="form" class="form form-horizontal" name="serverForm" novalidate>
                        <div class="form-body">
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">项目名称</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="form_control_1" ng-model="model.ProjectName" placeholder="请输入项目名称" required>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目名称是必填</span>
                                </div>
                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">GitLab地址</label>
                                <div class="col-md-10">
                                    <select disabled class="form-control" id="form_control_1" ng-model="model.Project" ng-change="GetProjectInfo(model.Project)" ng-options="project.name for project in ProjectList track by project.id">
                                    </select>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目地址是必填</span>
                                </div>
                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">Sln名称</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="form_control_1" ng-model="model.ProjectSlnName" placeholder="选择项目自动带出" required>
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">项目文件是必填</span>
                                </div>

                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">Csproj名称</label>
                                <div class="col-md-10">
                                    <input disabled type="text" class="form-control" id="ProjectCsprojName" ng-model="model.ProjectCsprojName" placeholder="请点击选择">
                                    <div class="form-control-focus">
                                    </div>
                                    <span class="help-block">Csproj是必选</span>
                                    
                                </div>

                            </div>
                            <div class="form-group form-md-line-input">
                                <label class="col-md-2 control-label" for="form_control_1">项目描述</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" rows="3" ng-model="model.ProjectDesc"></textarea>
                                    <div class="form-control-focus">
                                    </div>

                                </div>
                            </div>

                        </div>
                        <div class="form-actions right">
                            <a class="btn default" href="@Url.Action("Index","Project")">取消</a>
                            <a class="btn blue" ng-disabled="serverForm.$invalid" ng-click="SubmitFrom(model)"><i class="fa fa-check"></i> 保存</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <!--END Form -->
        <input type="hidden" id="id" value="@Html.ViewContext.RouteData.Values["id"]" />
    </div>
</div>
@section Scripts {
<script src="~/app/services/ProjectService.js"></script>
<script src="~/app/controllers/ProjectEdit.js"></script>
}

src/Uoko.FireProj.WebSite/Views/Project/Index.cshtml
@{
    ViewBag.Title = "项目管理";
   
}


<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Task")">首页</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Index", "Project")">项目</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">项目列表</a>
        </li>
    </ul>
</div>
<div ng-controller="ProjectController">
    <!-- Grid -->
        <div class="portlet box blue" ng-hide="isShowForm">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-github"></i>项目列表
                </div>
                <div class="tools">
                    <a href="javascript:;" class="reload" data-original-title="" title="刷新" ng-click="Query()"></a>
                </div>
                <div class="actions">
                    <a href="@Url.Action("Creat", "Project")" class="btn btn-default btn-sm">
                        <i class="fa fa-plus"></i> 创建项目
                    </a>    
                </div>
               
            </div>
            <div class="portlet-body">

                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>项目名称</th>
                            <th>Sln文件</th>
                            <th>Csproj文件</th>
                            <th>GitLab地址</th>
                            <th>项目描述</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="item in items">
                            <td><a  class="text-primary" href="/Project/Detail/{{item.Id}}">{{item.ProjectName}}</a></td>
                            <td>{{item.ProjectSlnName}}</td>
                            <td>{{item.ProjectCsprojName}}</td>
                            <td>{{item.ProjectRepo}}</td>
                            <td>{{item.ProjectDesc}}</td>
                            <td>
                                <div >
                                    <a ng-if="item.CreatorId==@ViewBag.UserId" class="btn btn-success btn-xs" href="/Project/Edit/{{item.Id}}">编辑</a>
                                    <a ng-if="item.CreatorId==@ViewBag.UserId" class="btn btn-success btn-xs" ng-click="delete(item)">删除</a>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table> 
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-right">
                            <uib-pagination total-items="totalItems" ng-model="currentPage" ng-change="Query()" first-text="首页" last-text="末页"
                                            previous-text="上一页" next-text="下一页" items-per-page="pageSize" max-size="5" boundary-links="true" boundary-link-numbers="true" rotate="false"></uib-pagination>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- Grid -->
</div>



@section Scripts {
    <script src="~/app/controllers/Project.js"></script>
<script src="~/app/services/ProjectService.js"></script>
}